export const PHOTO_HUNT_TASKS = [
  { id: 1, title: 'Szamárral a fabudiban', criteria: 'szamár, fabudi' },
  { id: 2, title: 'Egy csűrbe, szalmába', criteria: 'csűr, szalma' },
  { id: 3, title: 'Ásó, kapa, nagyharang', criteria: 'ásó, kapa, nagyharang' },
  { id: 4, title: 'Happy ending (videó)', criteria: 'kreatív' },
  { id: 5, title: 'Kép juhásszal + nyáj', criteria: 'juhász, nyáj' },
  { id: 6, title: 'Mezőségi a szervezőkkel (videó)', criteria: 'mezőségi néptánc' },
  { id: 7, title: 'Kürtőskalács a szervezőknek', criteria: 'kürtőskalács, szervezők' },
  { id: 8, title: 'Aranybárány', criteria: 'arany színű bárány' },
  { id: 9, title: 'Békacsókolás (videó)', criteria: 'béka, csókolás' },
  { id: 10, title: 'Mustkészítés lábbal (videó)', criteria: 'mustkészítés, lábbal' },
  { id: 11, title: 'Vajköpülés (videó)', criteria: 'vaj, köpülés' },
  { id: 12, title: 'Kecskefejés (videó)', criteria: 'kecske, fejés' },
  { id: 13, title: 'Kolbászokkal teli éléskamra', criteria: 'éléskamra, kolbászok' },
  { id: 14, title: 'Itassatok fröccsel egy szervezőt', criteria: 'fröccs, szervező' },
  { id: 15, title: 'Kép a legrégebbi szervezővel', criteria: 'Sancy' },
];